### ISSUE TITLE
90/150 order

### ISSUE THREAD

**Issue by msyriac** [ACTCollaboration/actsims#18]
How are we ensuring that the order of 90/150 in the pa3 stack is the same in the signal sims as in the noise sims?

EDIT: Upgrading this to a possible bug with high impact that needs to be fixed ASAP.

**Comment by msyriac** [comment]
The noise sims use the order provided by soapack.interfaces.ACTmr3.array_freqs. Do the signal sims do the same?

**Comment by dwhan89** [comment]
When the signal code generates alm_signal for pa3, it assumes 90-150 ordering. But that can be changed, and we can stack them whichever order we want. 

But whatever we do internally, I think the end product should have 90-150 ordering. So that end users always get the same ordering.

**Comment by msyriac** [comment]
Doesn't this mean there is a bug in the current implementation that Steve and lensers are using? The noise sim order is 150-90:
https://github.com/simonsobs/soapack/blob/master/soapack/interfaces.py#L224

The rationale behind 150-90 ordering is that if the 150 has index 0 in pa3, it will have index 0 in pa1 and pa2 as well.

**Comment by dwhan89** [comment]
Aren't we looping through frequency index here? https://github.com/ACTCollaboration/actsims/blob/master/actsims/simgen.py#L97 If so, I think we should be okay. Sim code returns one frequency at a time. So if we are looping frequency through in 150-90 order, we are fine.

**Comment by msyriac** [comment]
Ok, great, you're right, no bug here, the ordering is consistent.

**Comment by dwhan89** [comment]
Testing the code now. Will report back in an hour or two
