### ISSUE TITLE
Can't locate aveTools

### ISSUE THREAD

**Issue by dwhan89** [ACTCollaboration/actsims#4]
Hello, I was trying to run tryNoiseSims.py on NERSC, and I got the following error.

```
dwhan89@cori05:~/cori/workspace/actsims/actsims> python tryNoiseSims.py 
defualt_input_params_dir is /global/u2/d/dwhan89/cori/workspace/cmblens/cmblens/../inputParams
loading /global/u2/d/dwhan89/cori/workspace/cmblens/cmblens/../conf/logger.yaml
/global/homes/d/dwhan89/.local/cori/2.7-anaconda/lib/python2.7/site-packages/pyfits/__init__.py:22: PyFITSDeprecationWarning: PyFITS is deprecated, please use astropy.io.fits
  PyFITSDeprecationWarning)  # noqa
Traceback (most recent call last):
  File "tryNoiseSims.py", line 6, in <module>
    import aveTools
ImportError: No module named aveTools
```

I checked the permission aveTools.py. I am pretty sure I ran this script before, but it doesn't seem like I have read access to it. Can you please update the file permission (or include the file in the repository)?

```
dwhan89@cori05:~/cori/workspace/actsims/actsims> ls -lrt /global/homes/e/engelen/aveTools/aveTools.py
-rw-r----- 1 engelen engelen 32995 Oct 24 10:58 /global/homes/e/engelen/aveTools/aveTools.py
```

**Comment by ajvanengelen** [comment]
Just removed tryNoiseSims.py and trySignalSims.py from the repo.  These were local testing scripts that are probably not worth keeping in the repo.  The reason it was failing is that it was trying to load some utility routines that I wrote and just have locally (“ave” is my initials)

Alex

**Comment by dwhan89** [comment]
Ah, I see. I will pull it again. Thanks!

DW
